### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by retog** [fusepool/fusepool-dlc-patents#11]
Running eu.fusepool.rdfizer.marec.MarecRdfizerTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Cannot find CatalogManager.properties
Error on line 1 column 1 of file:/C:/Users/Reto/fusepool-platform/fusepool-dlc-patents/:
  SXXP0003: Error reported by XML parser: Content is not allowed in prolog.
Recoverable error on line 40
  FODC0002: org.xml.sax.SAXParseException; systemId:
  file:/C:/Users/Reto/fusepool-platform/fusepool-dlc-patents/; lineNumber: 1; columnNumber:
  1; Content is not allowed in prolog.
Error on line 1 column 1 of file:/C:/Users/Reto/fusepool-platform/fusepool-dlc-patents/:
  SXXP0003: Error reported by XML parser: Content is not allowed in prolog.
Recoverable error on line 38
  FODC0002: org.xml.sax.SAXParseException; systemId:
  file:/C:/Users/Reto/fusepool-platform/fusepool-dlc-patents/; lineNumber: 1; columnNumber:
  1; Content is not allowed in prolog.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.509 sec <<< FAILURE! - in eu.fusepool.rdfizer.marec.Ma
recRdfizerTest
epoXml(eu.fusepool.rdfizer.marec.MarecRdfizerTest)  Time elapsed: 1.456 sec  <<< ERROR!
java.lang.NullPointerException: null
        at eu.fusepool.rdfizer.marec.MarecRdfizer.transform(MarecRdfizer.java:88)
        at eu.fusepool.rdfizer.marec.MarecRdfizerTest.epoXml(MarecRdfizerTest.java:44)

Running eu.fusepool.rdfizer.marec.PatentXSLTProcessorTest
Error on line 1 column 1 of file:/C:/Users/Reto/fusepool-platform/fusepool-dlc-patents/:
  SXXP0003: Error reported by XML parser: Content is not allowed in prolog.
Recoverable error on line 40
  FODC0002: org.xml.sax.SAXParseException; systemId:
  file:/C:/Users/Reto/fusepool-platform/fusepool-dlc-patents/; lineNumber: 1; columnNumber:
  1; Content is not allowed in prolog.
Error on line 1 column 1 of file:/C:/Users/Reto/fusepool-platform/fusepool-dlc-patents/:
  SXXP0003: Error reported by XML parser: Content is not allowed in prolog.
Recoverable error on line 38
  FODC0002: org.xml.sax.SAXParseException; systemId:
  file:/C:/Users/Reto/fusepool-platform/fusepool-dlc-patents/; lineNumber: 1; columnNumber:
  1; Content is not allowed in prolog.
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.222 sec - in eu.fusepool.rdfizer.marec.PatentXSLTProce
ssorTest

Results :

Tests in error:
  MarecRdfizerTest.epoXml:44 ╗ NullPointer

> cat .\fusepool-dlc-patents\target\surefire-reports\eu.fusepool.rdfizer.marec.MarecRd
> ## fizerTest.txt
> ## Test set: eu.fusepool.rdfizer.marec.MarecRdfizerTest
> 
> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.509 sec <<< FAILURE! - in eu.fusepool.rdfizer.marec.M
> arecRdfizerTest
> epoXml(eu.fusepool.rdfizer.marec.MarecRdfizerTest)  Time elapsed: 1.456 sec  <<< ERROR!
> java.lang.NullPointerException: null
>         at eu.fusepool.rdfizer.marec.MarecRdfizer.transform(MarecRdfizer.java:88)
>         at eu.fusepool.rdfizer.marec.MarecRdfizerTest.epoXml(MarecRdfizerTest.java:44)

**Comment by luigiselmi** [comment]
I get the recoverable error messages but the tests don't fail. This is what I can see running MarcRdfizerTest:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Cannot find CatalogManager.properties
Error on line 1 column 1 of file:/home/luigi/projects/fusepool-platform/fusepool-dlc-patents/:
  SXXP0003: Error reported by XML parser: Content is not allowed in prolog.
Recoverable error on line 40 
  FODC0002: org.xml.sax.SAXParseException; systemId:
  file:/home/luigi/projects/fusepool-platform/fusepool-dlc-patents/; lineNumber: 1;
  columnNumber: 1; Content is not allowed in prolog.
Error on line 1 column 1 of file:/home/luigi/projects/fusepool-platform/fusepool-dlc-patents/:
  SXXP0003: Error reported by XML parser: Content is not allowed in prolog.
Recoverable error on line 38 
  FODC0002: org.xml.sax.SAXParseException; systemId:
  file:/home/luigi/projects/fusepool-platform/fusepool-dlc-patents/; lineNumber: 1;
  columnNumber: 1; Content is not allowed in prolog.

No NullPointerException

**Comment by retog** [comment]
strange....
