### ISSUE TITLE
User Rdfizers

### ISSUE THREAD

**Issue by retog** [fusepool/fusepool-dlc-patents#6]
Rdfization should be enabled. 

I think there should be one field for the URI, two radio boxes

0 Load RDF Data            0 Transform to RDF using VXXXXXXXXX

Where VXXXXXXXXX is a select box with the list of available Rdfizers

**Comment by luigiselmi** [comment]
Added bindings to rdfizers. The rdfizer can be selected from the UI when the user uploads an XML file. At the moment only the patent rdfizer is available.
